### ISSUE TITLE
ownership for vyos driver

### ISSUE THREAD

**Issue by dbarrosop** [napalm-automation-community/napalm-vyos#19]
Hello,
community drivers are going to be maintained by the community or considered deprecated and unmaintained. For that reason we are looking for people willing to maintain this repo. Owners will have full admin rights on this repo and on its pypy package.

Pinging top contributors to see if they are interested; @mirceaulinic 

If you have questions/comments let me know.

Regards

**Comment by mirceaulinic** [comment]
I unfortunately don't whatsoever with VyOS (to my shame, never hear of them actually before someone submitted this driver).
But I think @ppieprzycki has experience, so I will ping him to ask if he would like to volunteer to take care of this driver? Thanks!

**Comment by ppieprzycki** [comment]
@dbarrosop @mirceaulinic sure I'll do my best with this driver

**Comment by dbarrosop** [comment]
Done! :)
